<?php
//$Id$
/**
* @file
* A module that provides news services capability
*
*This module is for Mobylyze news
*/
/**
 * Implements hook_install().
 */
function newsservices_install() {
  // Set the weight to 3, making it heavier than Pathauto.
  db_update('system')
    ->fields(array(
        'weight' => 3,
      ))
    ->condition('type', 'module')
    ->condition('name', 'newsservices_mod')
    ->execute();
}
/**
 * Set the weight to 3
 */
function newsservices_update_7100() {
// Set the weight to 3, making it heavier than Pathauto.
  db_update('system')
    ->fields(array(
        'weight' => 3,
      ))
    ->condition('type', 'module')
    ->condition('name', 'newsservices_mod')
    ->execute();
}
/**
* Implements hook_services_resources
*/
function newsservices_services_resources() {
    return array(
        'news' => array(
          'index' => array (
            'help' => 'Retrieves a listing of news items',
            'file' => array('type' => 'inc', 'module' => 'newsservices'),
            'callback' => '_news_service_index',
            'access callback' => 'services_access_menu',
            'args' => array(
              array(
                'name' => 'page',
                'type' => 'int',
                'description' => '',
                'source' => array(
                  'data' => 'page',
                ),
                'optional' => TRUE,
                'default value' => 0,
              ),
              array(
                'name' => 'parameters',
                'type' => 'array',
                'description' => '',
                'source' => 'param',
                'optional' => TRUE,
                'default value' => array(),
              ),
            )
          )
        ),
    );
}
